### ISSUE TITLE
hi. do you have any video for explain ?

### ISSUE THREAD

**Issue by glerinsonum** [pyvim/pymaltego#1]
@pyvim

**Comment by dvemnt** [comment]
Hi, @glerinsonum. You mean videos for explanation that how works this package? Anyway I haven't any video.

**Comment by glerinsonum** [comment]
@pyvim 

I would like to knows How I can do and what I can do with this script that contains syntax of python. 

I love Maltego Program. Sincerely. Bro. Friend. 

I'm focused to Pipl.com https://github.com/piplcom/piplapis-python
I would your help. Tell me one example. That to learn how i can do I to have view the statistics of piplapis into Maltego. https://pipl.com/api/

There said email ( input ) clark.kent@example.com
Output. name, education, username, address.
Tell me and send me video, how I can works with python using pipl or another api for Maltego, or ruby.  be this favour voluntarity for me.
For the API key, is sample_key. 

![1](https://user-images.githubusercontent.com/21057103/28133593-da975f2a-6740-11e7-90d0-56c115c75f3d.png)

![gf](https://user-images.githubusercontent.com/21057103/28133881-95bcf9fe-6741-11e7-9ce4-e5274334916c.png)

https://pipl.com/api/guide/introduction

**Comment by glerinsonum** [comment]
@pyvim Make one video. To learn. How I can works with python. for Maltego.

**Comment by glerinsonum** [comment]
SDAS

**Comment by glerinsonum** [comment]
@pyvim SA

**Comment by glerinsonum** [comment]
Make one video. To learn. How I can works with python. for Maltego. 
CORDIALLY. THANK YOU.  @pyvim
